name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd gxnet; make
    - name: unit test
      run: cd gxnet; ./testbackward 
    - name: testseeds
      run: cd gxnet; ./testseeds
    - name: Install Python PIL
      run: pip install Pillow
    - name: Install Python numpy
      run: pip install numpy
    - name: launch mnist
      run: cd gxnet; sh launch_mnist.sh
